### ISSUE TITLE
(OAuth2) -> Error: invalid_request  Missing required parameter: scope

### ISSUE THREAD

**Issue by yairEO** [jaredhanson/passport-google-oauth#20]
I am doing everything as the guide says and I get to this Google error page which trying to connect with Google+. what's wrong?

**Comment by basickarl** [comment]
Must admit, Google is pretty bad with their documentation. Nothing beats a clear straight up example.

**Comment by iDVB** [comment]
Can anyone lend a hand with *where* to add this scope to?

**Comment by hugovart** [comment]
I have the same problem. It's not that I didn't add scope, I had a working app with `passport-google-oauth v0.1.5` and `passport v0.1.16` on `node v0.8`. The issue appeared since I updated to `node v0.10.38` and  `passport-google-oauth v0.2.0` and `passport v0.2.1`. I have scopes defined as `profile`, `email` and `https://mail.google.com/`

**Comment by hugovart** [comment]
Apparently this is related to upgrading to Connect 3+ (Express 4+). Still could not figure out a solution though.

**Comment by keith24** [comment]
See #80

**Comment by nik555max** [comment]
Hi i am getting this error. 

Error 400: invalid_request Missing required parameter: redirect_uri

can anyone help me with this ?
This error is occurring when i click on login with google button.
